version: 0.2

phases: 
  install:
    commands:
      - echo Executing Install Phase
    finally:
      - echo Executing Install Finally
  pre_build:
    commands:
      - echo Executing PreBuild Phase
    finally:
      - echo Executing Install Finally
  build:
    commands:
      - echo Executing Build Phase
    finally:
      - echo Executing Install Finally
  post_build:
    commands:
      - echo Executing PostBuild Phase
    finally:
      - echo Executing Install Finally
    