version: 0.2

phases: 
  install:
    commands:
      - echo Executing Install Phase
    finally:
      - echo Executing Install Finally
  pre_build:
    commands:
      - echo Executing PreBuild Phase
    finally:
      - echo Executing Install Finally
  build:
    commands:
      - echo Executing Build Phase
    finally:
      - echo Executing Install Finally
  post_build:
    commands:
      - echo Executing PostBuild Phase
    finally:
      - echo Executing Install Finally
    



    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>


              <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="/">Home</a>
                    <a class="dropdown-item" href="/projects">Projects</a>
                    <a class="dropdown-item" href="/login">Visitor Log</a>
                  </div>     
                </li>
              </ul>
            </div>
          </nav>